### ISSUE TITLE
undefined reference to `PocuterLib::HAL::esp32_c3_OTA::getCurrentAppID()'

### ISSUE THREAD

**Issue by ednieuw** [pocuter/ArduinoBoard#1]
I updated my pocuter library in the sketch folder with the latest 1.2-2.0.3-RC1.
To avoid unexpected compile errors when a library is updated I prefer to update the library by hand from:  C:\Program Files (x86)\Arduino\libraries\Pocuter

To avoid crashes with pocuter->ugui->UG_PutChar statement I had to disble the SD-card in the PocuterLibConfig.h 
#define POCUTER_DISABLE_SD_CARD
when the SD-card is disabled the following error occurs.
c:/users/ednie/appdata/local/arduino15/packages/esp32/tools/riscv32-esp-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld.exe: C:\Users\ednie\AppData\Local\Temp\arduino_build_424951\libraries\Pocuter\Pocuter.cpp.o: in function `PocuterConfig::PocuterConfig(unsigned char const*, unsigned long long*)':

C:\Users\ednie\Documents\Files\Arduino\libraries\Pocuter\src/hal/PocuterConfig.cpp:28: undefined reference to `PocuterLib::HAL::esp32_c3_OTA::getCurrentAppID()'

Lucky for me I do not have to disable the SD-card anymore with this version!
BTW I compile in the Arduino IDE 1.8.19 with ESP 2.0.5 for a ESP32-C3 DEV module and huge APP partition scheme in W11.
